[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-merkle"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "62f726c2f0b5f4d5bb6a5f66c3f577d518100ed4"}

# lazy_static = "1"
# lockfree-object-pool = "0.1"

[dev-dependencies]
ark-ff = "0.3"
