[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-merkle"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "3f5f90d190f537857c800a9aeb349bff2132d175"}

ark-ff = "0.3"
lockfree-object-pool = "0.1"
num = "0.4"
once_cell = "1"

[dev-dependencies]

# RocksDB cannot build with the wasm target
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
rocksdb = "0.18.0"
