[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-merkle"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "a37e9b9a94d9b77c5b69b0dc64788b8c0e0973f0"}

lockfree-object-pool = "0.1"
once_cell = "1"

[dev-dependencies]
ark-ff = "0.3"
