[package]
name = "bin_prot_checker"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
structopt = "0.3.21"
bin-prot = { path = "../bin-prot" }
erased-serde = "0.3.15"
