[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "wire-type-derive"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"

darling = "0.13.0"

[dev-dependencies]
wire-type = {path = "../wire-type"}

serde = {version = "1", features = ["derive"]}
