[workspace]
members = [
  "base",
  "consensus",
  "crypto",
  "merkle",
  "snark-keys",
  "protocol/bin-prot",
  "protocol/wire-type",
  "protocol/bin_prot_checker",
  "protocol/wire-type-derive",
  "protocol/test-fixtures",
  "protocol/test-serialization",
]
