[workspace]
members = [
	"base",
	"consensus",
	"crypto",
	# All crates related to bin prot wire protocol
	"protocol/bin-prot",
	"protocol/wire-type",
	"protocol/bin_prot_checker",
	"protocol/wire-type-derive",
	"protocol/test-fixtures",
	"protocol/test-serialization",
	# binaries - entry points for an end user
	"apps/cli"
]
