[workspace]
members = [
  "base",
  "consensus",
  "crypto",
  "network",
  "snark-keys",
  "protocol/bin-prot",
  "protocol/bin_prot_checker",
  "protocol/test-fixtures",
  "protocol/test-serialization",
]
# This is still needed for virtual workspaces 
# per <https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html#details>
resolver = "2"
