[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-serialization-types"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = {path = "../bin-prot"}
versioned = {path = "../versioned"}

serde = {version = "1", features = ["derive"]}

[dev-dependencies]
test-fixtures = {path = "../test-fixtures"}

pretty_assertions = "1"
wasm-bindgen-test = "0.3"
