[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-serialization-types"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = {path = "../bin-prot"}
versioned = {path = "../versioned"}

serde = {version = "1", features = ["derive"]}
mina-signer = {git = "https://github.com/willemolding/proof-systems", rev = "d4e311e3c7dc7e6ad6bd42dc2a23bbc7093335ce"}
o1-utils = {git = "https://github.com/willemolding/proof-systems", rev = "d4e311e3c7dc7e6ad6bd42dc2a23bbc7093335ce"}

[dev-dependencies]
test-fixtures = {path = "../test-fixtures"}

pretty_assertions = "1"
wasm-bindgen-test = "0.3"
