[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "proof-systems"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "52b859e9b5d81e94c4bc0e03cc66d4128419e7d6"}
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "52b859e9b5d81e94c4bc0e03cc66d4128419e7d6"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "52b859e9b5d81e94c4bc0e03cc66d4128419e7d6"}
