[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "proof-systems"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "6eb73b4e195c89efba5f9d8fc7678675f63281cc"}
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "6eb73b4e195c89efba5f9d8fc7678675f63281cc"}
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "6eb73b4e195c89efba5f9d8fc7678675f63281cc"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "6eb73b4e195c89efba5f9d8fc7678675f63281cc"}

anyhow = "1"
ark-ff = "0.3"
bitvec = "1"
num = "0.4"
