[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "proof-systems"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "387115d9d88f781b64d6b328ed01b2d6d63c998d"}
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "387115d9d88f781b64d6b328ed01b2d6d63c998d"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "387115d9d88f781b64d6b328ed01b2d6d63c998d"}
