[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "proof-systems"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "fef5cfe909f6f297f6d8e9b3b4a128f23c9b24f3"}
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "fef5cfe909f6f297f6d8e9b3b4a128f23c9b24f3"}
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "fef5cfe909f6f297f6d8e9b3b4a128f23c9b24f3"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "fef5cfe909f6f297f6d8e9b3b4a128f23c9b24f3"}

anyhow = "1"
ark-ff = "0.3"
bitvec = "1"
derive_more = "0.99"
num = "0.4"
serde = {version = "1", features = ["derive"]}

[dev-dependencies]
serde_json = "1"
