[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-wasm-mvp"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[features]
default = []

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
env_logger = "0.9"
hex = "0.4"
js-sys = "0.3"
libp2p = "0.43"
libp2p-mplex = "0.32"
multihash = "0.16"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
libp2p = {version = "0.43", features = ["wasm-bindgen", "wasm-ext-websocket"]}

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
opt-level = 's'
