[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-wasm-mvp"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

publish = false

[features]
default = []

[dependencies]
mina-consensus = {path = "../../../consensus"}
mina-network = {path = "../../../network"}
mina-serialization-types = {path = "../../../protocol/serialization-types"}

anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
hex = "0.4"
js-sys = "0.3"
lazy_static = "1"
libp2p = {version = "0.44", features = ["wasm-bindgen", "wasm-ext-websocket"]}
log = "0.4"
protobuf = {version = "3", features = ["with-bytes"]}
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
reqwest = { version = "0.11.0", features = ["json"] }

[dev-dependencies]

[build-dependencies]
anyhow = "1"
protobuf-codegen = "3"
walkdir = "2"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
opt-level = 's'
