[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-wasm-mvp"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

publish = false

[features]
default = []

[dependencies]
mina-consensus = { workspace = true }
mina-network = { workspace=true }
mina-rs-base = { workspace = true }
mina-serialization-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
js-sys = { workspace = true }
lazy_static = { workspace = true }
libp2p = { version = "0.44", features = ["wasm-bindgen", "wasm-ext-websocket"] }
log = { workspace = true }
protobuf = { workspace = true }
reqwest = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]

[build-dependencies]
anyhow = "1"
protobuf-codegen = "3"
walkdir = "2"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
opt-level = 's'
