[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-wasm-mvp"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

publish = false

[features]
default = []

[dependencies]
mina-network = {path = "../../../network"}

anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
hex = "0.4"
js-sys = "0.3"
libp2p = {version = "0.43", features = ["wasm-bindgen", "wasm-ext-websocket"]}
libp2p-mplex = "0.32"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
opt-level = 's'
