[package]
name = "wire-type"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.126" }
wire-type-derive = { path = "../wire-type-derive" }

[dev-dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.68"
