[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-network"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[features]
default = []

[dependencies]
cfg-if = "1"
lazy_static = "1"
libp2p = {version = "0.42", features = ["dns-tokio", "tcp-tokio"]}
libp2p-mplex = {version = "0.31"}
multihash = "0.16"
async-io = "1.3.1"
futures = "0.3.13"
env_logger = "0.9.0"

[dev-dependencies]
anyhow = "1"
async-std = { version = "1.9.0", features = ["attributes"] }
env_logger = "0.9.0"
tokio = { version = "1.15", default-features = false, features = ["macros", "rt", "rt-multi-thread", "time"] }

# To list all wasm targets, use command 'rustc --print target-list | grep wasm'
[target.'cfg(target_arch = "wasm32")'.dependencies]
libp2p = {version = "0.42", features = ["wasm-bindgen", "wasm-ext-websocket"]}

getrandom = {version = "0.2", features = ["js"]}
js-sys = "0.3"
wasm-bindgen = "0.2"

# nix is one of the indirect dependencies of libp2p
# patch its version to dismiss errors from 'cargo deny check advisories'
# this can be removed once unstream crate(s) are updated
# [patch.crates-io]
# nix = "0.22.2"
