[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-network"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
getrandom = {version = "0.2", features = ["js"]}
lazy_static = "1"
multihash = "0.15"

# switch back to published versions once libp2p-mplex 0.30.1 or above is published
libp2p = {git = "https://github.com/libp2p/rust-libp2p", version = "0.42", rev = "30fc8820373ddbaa44568cdd780bc82e8fdc4f76"}
libp2p-mplex = {git = "https://github.com/libp2p/rust-libp2p", version = "0.31", rev = "30fc8820373ddbaa44568cdd780bc82e8fdc4f76"}

[dev-dependencies]
async-std = "1"
