[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-network"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[features]
default = []

[dependencies]
cfg-if = "1"
lazy_static = "1"
multihash = "0.15"

# switch back to published versions once libp2p-mplex 0.30.1 or above is published
libp2p = {git = "https://github.com/libp2p/rust-libp2p", version = "0.42", rev = "fad99808ac708f0d55f72b12037dec3ef3678547", features = ["dns-tokio", "tcp-tokio"]}
libp2p-mplex = {git = "https://github.com/libp2p/rust-libp2p", version = "0.31", rev = "fad99808ac708f0d55f72b12037dec3ef3678547"}

[dev-dependencies]
anyhow = "1"
tokio = {version = "1.15", features = ["rt", "macros"]}

# To list all wasm targets, use command 'rustc --print target-list | grep wasm'
[target.'cfg(target_arch = "wasm32")'.dependencies]
libp2p = {git = "https://github.com/libp2p/rust-libp2p", version = "0.42", rev = "fad99808ac708f0d55f72b12037dec3ef3678547", features = ["wasm-bindgen", "wasm-ext-websocket"]}

getrandom = {version = "0.2", features = ["js"]}
js-sys = "0.3"
wasm-bindgen = "0.2"

# nix is one of the indirect dependencies of libp2p
# patch its version to dismiss errors from 'cargo deny check advisories'
# this can be removed once unstream crate(s) are updated
[patch.crates-io]
nix = "0.22.2"
