[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-network"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
getrandom = {version = "0.2", features = ["js"]}
lazy_static = "1"
multihash = "0.15"
env_logger = "0.9.0"

# switch back to published versions once libp2p-mplex 0.30.1 or above is published
libp2p = {git = "https://github.com/libp2p/rust-libp2p", version = "0.42", rev = "fad99808ac708f0d55f72b12037dec3ef3678547"}
libp2p-mplex = {git = "https://github.com/libp2p/rust-libp2p", version = "0.31", rev = "fad99808ac708f0d55f72b12037dec3ef3678547"}


[dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dev-dependencies]
async-std = "1"

# nix is one of the indirect dependencies of libp2p
# patch its version to dismiss errors from 'cargo deny check advisories'
# this can be removed once unstream crate(s) are updated
[patch.crates-io]
nix = "0.22.2"
