#!/bin/bash

PAT_APA="^// Copyright 2020 ChainSafe Systems // SPDX-License-Identifier: Apache-2.0$"
PAT_CODEGEN="^// This file is generated by "

valid=true
for file in $(find . -type f -not -path "**/target/*" -not -path "**/node_modules/*" -not -path "./apps/wasm/**/dist/*" -not -path "./apps/wasm/**/pkg/*" | egrep '\.([rtj]s)$'); do
	header=$(echo $(head -3 $file))
	if !(echo "$header" | grep -q "$PAT_APA") && !(echo "$header" | grep -q "$PAT_CODEGEN"); then
		echo "$file was missing header"
		cat ./scripts/copyright.txt $file > temp
		mv temp $file
		valid=false
	fi
done

# if a header is incorrect, return an OS exit code
if [ "$valid" = false ] ; then
	exit 1
fi
