// This file is generated by rust-protobuf 3.0.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `messages.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_1;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:PeerStatus)
pub struct PeerStatus {
    // message fields
    // @@protoc_insertion_point(field:PeerStatus.connected)
    pub connected: bool,
    // @@protoc_insertion_point(field:PeerStatus.peer_id)
    pub peer_id: ::std::string::String,
    // @@protoc_insertion_point(field:PeerStatus.sync_status)
    pub sync_status: ::std::string::String,
    // @@protoc_insertion_point(field:PeerStatus.protocol_state_hash)
    pub protocol_state_hash: ::std::string::String,
    // @@protoc_insertion_point(field:PeerStatus.git_commit)
    pub git_commit: ::std::string::String,
    // @@protoc_insertion_point(field:PeerStatus.uptime_minutes)
    pub uptime_minutes: i64,
    // special fields
    // @@protoc_insertion_point(special_field:PeerStatus.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PeerStatus {
    fn default() -> &'a PeerStatus {
        <PeerStatus as ::protobuf::Message>::default_instance()
    }
}

impl PeerStatus {
    pub fn new() -> PeerStatus {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connected",
            |m: &PeerStatus| { &m.connected },
            |m: &mut PeerStatus| { &mut m.connected },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "peer_id",
            |m: &PeerStatus| { &m.peer_id },
            |m: &mut PeerStatus| { &mut m.peer_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sync_status",
            |m: &PeerStatus| { &m.sync_status },
            |m: &mut PeerStatus| { &mut m.sync_status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "protocol_state_hash",
            |m: &PeerStatus| { &m.protocol_state_hash },
            |m: &mut PeerStatus| { &mut m.protocol_state_hash },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "git_commit",
            |m: &PeerStatus| { &m.git_commit },
            |m: &mut PeerStatus| { &mut m.git_commit },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uptime_minutes",
            |m: &PeerStatus| { &m.uptime_minutes },
            |m: &mut PeerStatus| { &mut m.uptime_minutes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PeerStatus>(
            "PeerStatus",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PeerStatus {
    const NAME: &'static str = "PeerStatus";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connected = is.read_bool()?;
                },
                18 => {
                    self.peer_id = is.read_string()?;
                },
                26 => {
                    self.sync_status = is.read_string()?;
                },
                34 => {
                    self.protocol_state_hash = is.read_string()?;
                },
                42 => {
                    self.git_commit = is.read_string()?;
                },
                48 => {
                    self.uptime_minutes = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.connected != false {
            my_size += 1 + 1;
        }
        if !self.peer_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.peer_id);
        }
        if !self.sync_status.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.sync_status);
        }
        if !self.protocol_state_hash.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.protocol_state_hash);
        }
        if !self.git_commit.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.git_commit);
        }
        if self.uptime_minutes != 0 {
            my_size += ::protobuf::rt::int64_size(6, self.uptime_minutes);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.connected != false {
            os.write_bool(1, self.connected)?;
        }
        if !self.peer_id.is_empty() {
            os.write_string(2, &self.peer_id)?;
        }
        if !self.sync_status.is_empty() {
            os.write_string(3, &self.sync_status)?;
        }
        if !self.protocol_state_hash.is_empty() {
            os.write_string(4, &self.protocol_state_hash)?;
        }
        if !self.git_commit.is_empty() {
            os.write_string(5, &self.git_commit)?;
        }
        if self.uptime_minutes != 0 {
            os.write_int64(6, self.uptime_minutes)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PeerStatus {
        PeerStatus::new()
    }

    fn clear(&mut self) {
        self.connected = false;
        self.peer_id.clear();
        self.sync_status.clear();
        self.protocol_state_hash.clear();
        self.git_commit.clear();
        self.uptime_minutes = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PeerStatus {
        static instance: PeerStatus = PeerStatus {
            connected: false,
            peer_id: ::std::string::String::new(),
            sync_status: ::std::string::String::new(),
            protocol_state_hash: ::std::string::String::new(),
            git_commit: ::std::string::String::new(),
            uptime_minutes: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PeerStatus {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PeerStatus").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PeerStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PeerStatus {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0emessages.proto\"\xda\x01\n\nPeerStatus\x12\x1c\n\tconnected\x18\
    \x01\x20\x01(\x08R\tconnected\x12\x17\n\x07peer_id\x18\x02\x20\x01(\tR\
    \x06peerId\x12\x1f\n\x0bsync_status\x18\x03\x20\x01(\tR\nsyncStatus\x12.\
    \n\x13protocol_state_hash\x18\x04\x20\x01(\tR\x11protocolStateHash\x12\
    \x1d\n\ngit_commit\x18\x05\x20\x01(\tR\tgitCommit\x12%\n\x0euptime_minut\
    es\x18\x06\x20\x01(\x03R\ruptimeMinutesb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PeerStatus::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
