[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-consensus"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-crypto = {version = "0.1.0", path = "../crypto"}
mina-rs-base = {version = "0.1.0", path = "../base"}

hex = "0.4"
thiserror = "1"

[dev-dependencies]
base64 = "0.13"
wasm-bindgen-test = "0.3"
quickcheck = "1"
proptest = "1.0.0"
rand = "0.8.4"
