[package]
name = "mina-consensus"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
blake2-rfc = { version = "0.2.18" }
mina-crypto = { version = "0.1.0", path = "../crypto" }
mina-rs-base = { version = "0.1.0", path = "../base" }
serde-bin-prot = { git = "https://github.com/ChainSafe/serde-bin-prot", branch = "main" }
thiserror = "1.0.24"
