[package]
name = "blocks-crawler"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mina-rs-base = {path = "../../../base"}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
reqwest = { version = "0.11.0", features = ["json"] }
tokio = {version = "1.18", features = ["macros", "rt", "rt-multi-thread", "sync"]}
log = "0.4"
env_logger = "0.9.0"
futures = "0.3.21"
clap = { version = "3.0", features = ["derive"] }
