[package]
name = "mina-rs-base"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
wire-type = {path = "../protocol/wire-type" }

mina-crypto = { path = "../crypto" }

anyhow = "1"
blake2 = "0.9"
chrono = "0.4"
derive_deref = "1.1"
num = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1"