[package]
name = "mina-rs-base"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
wire-type = {path = "../wire-type" }
mina-crypto = { path = "../crypto" }
bin-prot = {path = "../bin-prot" } # remove this once working bee is complete
