[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-base"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-crypto = {path = "../crypto"}
wire-type = {path = "../protocol/wire-type"}

derive_deref = "1.1"
num = "0.4"
serde = {version = "1", features = ["derive"]}
thiserror = "1"
time = "0.3"

ark-ec = "0.3.0"
ark-ff = "0.3.0"
commitment_dlog = {git = "https://github.com/o1-labs/proof-systems", rev = "81a61f9e345fad6d2a652fb323a882f39c6c1057"}
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "81a61f9e345fad6d2a652fb323a882f39c6c1057"}
plonk_circuits = {git = "https://github.com/o1-labs/proof-systems", rev = "81a61f9e345fad6d2a652fb323a882f39c6c1057"}
plonk_protocol_dlog = {git = "https://github.com/o1-labs/proof-systems", rev = "81a61f9e345fad6d2a652fb323a882f39c6c1057"}

# This dependency is not used by the crate, but is a subdependency of commitment_dlog
# This features must be enable to build with WASM support
# It has no effect for normal builds
getrandom = {version = "0.2", features = ["js"]}
