[package]
name = "mina-rs-base"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
wire-type = {path = "../wire-type" }
mina-crypto = { path = "../crypto" }

plonk_protocol_dlog = { git = "https://github.com/o1-labs/proof-systems" }
plonk_circuits = { git = "https://github.com/o1-labs/proof-systems" }
commitment_dlog = { git = "https://github.com/o1-labs/proof-systems" }
mina-curves = { git = "https://github.com/o1-labs/proof-systems" }
ark-ec = "0.3.0"
ark-ff = "0.3.0"
