[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-rs-base"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-crypto = {path = "../crypto"}
wire-type = {path = "../protocol/wire-type"}

anyhow = "1"
derive_deref = "1.1"
num = "0.4"
serde = {version = "1", features = ["derive"]}
thiserror = "1"
time = "0.3"
