[package]
name = "mina-rs-base"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
sha2 = "0.9.5"
