[package]
name = "mina-rs-base"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2021"

[dependencies]
wire-type = {path = "../protocol/wire-type" }

mina-crypto = { path = "../crypto" }

anyhow = "1"
blake2 = "0.9"
chrono = "0.4"
derive_deref = "1.1"
num = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

plonk_protocol_dlog = { git = "https://github.com/o1-labs/proof-systems" }
plonk_circuits = { git = "https://github.com/o1-labs/proof-systems" }
commitment_dlog = { git = "https://github.com/o1-labs/proof-systems" }
mina-curves = { git = "https://github.com/o1-labs/proof-systems" }
ark-ec = "0.3.0"
ark-ff = "0.3.0"

# This dependency is not used by the crate but is a subdependency of commitment_dlog
# This features must be enable to build with WASM support
# It has no effect for normal builds
getrandom = { version = "0.2", features = ["js"] }
