[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "wire-type-2"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
wire-type-derive = {path = "../wire-type-derive"}

serde = {version = "1"}

[dev-dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
