[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-sdk"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-rs-base = {path = "../base"}

serde = "1.0.136"
serde_json = "1.0.79"

[dev-dependencies]
proof-systems = {path = "../proof-systems-shim"}
