[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "bin_prot_checker"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = { workspace = true }

serde = { workspace = true }
structopt = {workspace=true}
