[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "bin_prot_checker"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = {path = "../bin-prot"}

erased-serde = "0.3.15"
serde = {version = "1", features = ["derive"]}
structopt = "0.3.21"
