[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-crypto"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[features]
default = []

# browser feature is used to run wasm tests in headless browser context
browser = []

[dependencies]
bin-prot = {path = "../protocol/bin-prot"}
wire-type = {path = "../protocol/wire-type"}

mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "b7495933e70ae078eddedc43c59f867cb9bb78da"}
# o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "b7495933e70ae078eddedc43c59f867cb9bb78da"}
oracle = {git = "https://github.com/o1-labs/proof-systems", rev = "b7495933e70ae078eddedc43c59f867cb9bb78da"}

ark-ec = "0.3"
ark-serialize = "0.3"
base64 = "0.13"
blake2 = "0.10"
bs58 = {version = "0.4", features = ["check"]}
derive_deref = "1.1"
derive_more = "0.99"
serde = {version = "1", features = ["derive"]}
thiserror = "1"

[dev-dependencies]
ark-ff = "0.3"
num-bigint = "0.4"
wasm-bindgen-test = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
