[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-crypto"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = {path = "../protocol/bin-prot"}
wire-type = {path = "../protocol/wire-type"}

blake2 = "0.9.1"
bs58 = {version = "0.4.0", features = ["check"]}
derive_deref = "1.1"
serde = {version = "1", features = ["derive"]}
thiserror = "1.0.25"
