[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-crypto"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
bin-prot = {path = "../protocol/bin-prot"}
mina-network-types = {path = "../protocol/network-types"}
versioned = {path = "../protocol/versioned"}

base64 = "0.13"
blake2 = "0.10"
bs58 = {version = "0.4", features = ["check"]}
hex = "0.4"
num = "0.4"
derive_deref = "1.1"
derive_more = "0.99"
serde = {version = "1", features = ["derive"]}
thiserror = "1"
