[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-crypto"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[features]
default = []

# browser feature is used to run wasm tests in headless browser context
browser = []

[dependencies]
bin-prot = {path = "../protocol/bin-prot"}
mina-serialization-types = {path = "../protocol/serialization-types"}
versioned = {path = "../protocol/versioned"}

mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "9a1c4852c11f04f54e5e71b050af02e5586bb698"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "9a1c4852c11f04f54e5e71b050af02e5586bb698"}
oracle = {git = "https://github.com/o1-labs/proof-systems", rev = "9a1c4852c11f04f54e5e71b050af02e5586bb698"}

ark-ec = "0.3"
ark-ff = "0.3"
base64 = "0.13"
blake2 = "0.10"
bs58 = {version = "0.4", features = ["check"]}
hex = "0.4"
num = "0.4"
derive_deref = "1.1"
derive_more = "0.99"
serde = {version = "1", features = ["derive"]}
thiserror = "1"

[dev-dependencies]
ark-ff = "0.3"
num-bigint = "0.4"
wasm-bindgen-test = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
