[package]
name = "mina-crypto"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
sha2 = "0.9.5"
bs58 = { version = "0.4.0", features = ["check"] }
serde = { version = "1.0.126", features = ["derive"] }
serde-versions-derive = "0.0.4"
serde-bin-prot = { git = "https://github.com/ChainSafe/serde-bin-prot", branch = "main" }
const_format = "0.2.14"
