[package]
name = "mina-crypto"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
bs58 = { version = "0.4.0", features = ["check"] }
serde = { version = "1.0.126", features = ["derive"] }
serde-versions-derive = "0.0.4"
bin-prot = { path = "../bin-prot" }
thiserror = "1.0.25"
blake2 = "0.9.1"
