on: [push, pull_request]

name: Check Licence

jobs:
  check-licence:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Check license
        run: |
          sh ./scripts/add_license.sh
