[package]
authors = ["ChainSafe Systems <info@chainsafe.io>"]
name = "mina-secrets"
version = "0.1.0"

edition = "2021"
license = "Apache-2.0"

[dependencies]
mina-crypto = {path = "../crypto"}

mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "81a61f9e345fad6d2a652fb323a882f39c6c1057"}

argon2 = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
bs58 = {version = "0.4", features = ["check"]}
derive_more = "0.99"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1"
xsalsa20poly1305 = "0.8"

[dev-dependencies]
hex = "0.4"

[lib]
